export const FETCH_ALL_BUILDINGS_REQUEST = 'FETCH_ALL_BUILDINGS_REQUEST';
export const FETCH_ALL_BUILDINGS_SUCCESS = 'FETCH_ALL_BUILDINGS_SUCCESS';
export const FETCH_ALL_BUILDINGS_ERROR = 'FETCH_ALL_BUILDINGS_ERROR';